version: 0.2
env:
  variables:
    PROJECT_NAME: "training-cicd-aws-s3-demo-react"
    REGION: "sa-east-1"
phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - echo Installing all requirements
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  base-directory: build
  files:
    - '**/*'